# Deep Learning with Python Personal Notebook.

## What is deep learning?

**Deep learning is a mathematical framework for learning representations from data. A multistage way to learn data representation**

Learning representation from Data: To do machine learning we need three things: 
- Inputs.
- example of the expected results and 
- a way to measure if the algorithm is doing well.

Deep learning is a specific subfield of machine learning: a new take on learning *representations* from data that puts an emphasis on learning successive layers of increasingly meaningful *representations.*

**What is representation?** At its core, its a different way to look at data-- to represent or encode data. For instance, an image can be represented or encoded in the RBG format or HSV format. These are two representation of the same data.

Machine-learning models are all about finding appropriate representations
for their input data—transformations of the data that make it more amenable
to the task at hand, such as a classification task..


The specification of what a layer does to its input data is stored the layers **weight**, which are a bunch of numbers. "The transformation implemented by its layer is *parametized* by its weight.

**Loss Function**:How the network will be able to measure its performance on
the training data, and thus how it will be able to steer itself in the right direction.

**Optimizer**:The mechanism through which the network will update itself
based on the data it sees and its loss function.

**Class**: A category of a classification problem. eg, Sunny, rainy, snowy day of the week in one city-- Lagos

**Samples**: Data points

**Label**: A class associated with a specific sample. Allows us to differentiate our data. eg. city. Lagos.

>Example instance. Weather prediction. Class: Sunny, Rainy. Label: Sunny or rain in a Lagos.

**Layer**: The core building block of a neural network. Layer extract representation out of the data fed to them.








## Data Representation of Neural Networks

**Tensors**: A container of data.

**Scalars** (0D tensors): A tensor that contains only one number

**ndim**: Display the number of axes of Numpy tensor.

```
import numpy as np
x = np.array(20)
>>> x
array(12)
>>> x.ndim
0
```
**Vectors**: An array of numbers is called a vector. *1D tensor*.
```
>>> x = np.array([12, 3, 6, 14])
>>> x
array([12, 3, 6, 14])
>>> x.ndim
1
```
Where x is a *1D tensor* and *4 dimensional 4D vector*.

**Matrices:** An array of vectors or 2D tensor. A matrix has two axes.
```
>>> x = np.array([[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]])
>>> x.ndim
2
```
**3D tensors and higher-dimensional tensors**: If you pack matrix or an array of vectors or 2D tensor into an array.
```
>>> x = np.array([[[5, 78, 2, 34, 0],
                    [6, 79, 3, 35, 1],
                    [7, 80, 4, 36, 2]],

                    [[5, 78, 2, 34, 0],
                    [6, 79, 3, 35, 1],
                    [7, 80, 4, 36, 2]],

                    [[5, 78, 2, 34, 0],
                    [6, 79, 3, 35, 1],
                    [7, 80, 4, 36, 2]]])
>>> x.ndim
3
```

**Key attributes**: A tensor is defined by three key attributes


*   *Number of axes*:
*   *Shape:* This is a tuple of number that describes how many dimensions the tensor has along each axis. For instance `x` has shape `(3,3,5)`. A vector has a shape with a single number.
*   Datatype 



##  Manipulating Tensor in Numpy
```
>>> my_slice = sample_images[10:100]
>>> print(my_slice.shape)
(90, 28, 28)
```

It’s equivalent to this more detailed notation, which specifies a `start index` and `stop index` for the slice along each tensor axis. Note that `:` is equivalent to selecting the entire axis:
```
>>> my_slice = train_images[10:100, :, :]
>>> my_slice.shape
(90, 28, 28)
>>> my_slice = train_images[10:100, 0:28, 0:28]
>>> my_slice.shape
(90, 28, 28)
```
In general, you may select between any two indices along each tensor axis. For
instance, in order to select `14 × 14 `pixels in the bottom-right corner of all images, you
do this:
```
my_slice = train_images[:, 14:, 14:]
```

## The notion of data batches

Deep-learning models don’t process an entire dataset at once; rather,
they break the data into small batches. Concretely, here’s one batch of our MNIST digits, with batch size of 128:
```
batch = train_images[:128]
```
And here’s the next batch:
```
batch = train_images[128:256]
```
The nth batch
```
batch_n = train_images[128 * n:128 * (n + 1)]
```

## Real-world examples of data tensors

* Vector data—2D tensors of shape `(samples, features)`
* Timeseries data or sequence data—3D tensors of shape `(samples, timesteps,
features)`
* Images—4D tensors of shape `(samples, height, width, channels)` or `(samples,
channels, height, width)`
* Video—5D tensors of shape `(samples, frames, height, width, channels)` or
`(samples, frames, channels, height, width)`

## Vector of data

An actual dataset of farmers, where we consider each farmer's age, farm size,
and income. Each farmer can be characterized as a vector of 3 values, and thus
an entire dataset of 100,000 farmers can be stored in a 2D tensor of shape
(100000, 3).

In [ ]:
import numpy as np

np.zeros((64,3,32,10))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0.

## The gears of neural networks: tensor operations

### Element-wise Operation: 
Define a naive implementation of `relu` function in python
```
output = relu(dot(W * input) + b)
relu = max(x,0)
```


In [ ]:
def naive_relu(x):
  assert len(x.shape) == 2    # 2D tensor

  x = x.copy()                # avoid overwriting the input tensor
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j],0)

  return x

In [ ]:
def naive_add(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]
      
  return x

### Broadcasting

In [ ]:
def naive_add_matrix_vector(x,y):
  assert len(x.shape) == 2        # 2D tensor
  assert len(y.shape) == 1        # vector
  assert x.shape[1] == y.shape[0] 

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[j]
  return x

# Numpy implementation of broadcasting
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

### Tensor dot
The dot operation, also called a tensor product (not to be confused with an elementwise product) is the most common, most useful tensor operation. Contrary to element-wise operations, it combines entries in the input tensors.

```
import numpy as np
z = np.dot(x, y)
```


In [ ]:
def naive_vector_dot(x,y):
  '''
  dot product between two vectors
  '''
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]

  z = 0.
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z


def naive_matrix_vector_dot(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  z = np.zero(x.shape[0])

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] += x[i,j] * y[i]
  
  return z

### Tensor Reshaping
Reshaping a tensor means rearranging its rows and columns to match a target shape.
Naturally, the reshaped tensor has the same total number of coefficients as the initial
tensor. Reshaping is best understood via simple examples:


In [ ]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

x.reshape(6,1)
x.reshape(2,3)

x

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [ ]:
x[:,1]

array([1., 3., 5.])

In [ ]:
x[1,:]

array([2., 3.])

In [ ]:
x =np.transpose(x)
x

array([[0., 2., 4.],
       [1., 3., 5.]])

In [ ]:
x[:,1]

array([2., 3.])

In [ ]:
x[1,:]

array([1., 3., 5.])